### PR TITLE
Compatibility updates for TT-RSS as of Dec. 14, 2017.

### PR DESCRIPTION
**Pull request by dzaikos**
Patches for PDO changes, Article class changes, and fixed global/class constant NS bug.

### CODE REVIEW

**Comment by zaubererty** [comment]
Worked for me

**Comment by andreimarcu** [comment]
Thanks for the fix! Worked perfectly

**Comment by shinymimiq** [comment]
Works for me. Thanks for the fix!

**Comment by dzaikos** [comment]
Closing because this is repo is dead.

**Pull request closed without merging**
